language: node_js
node_js:
  - "7"
sudo: false
dist: trusty
before_install:
  - gem install zendesk_apps_tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
env:
  - TASK=test
  - TASK=srcclr
  - TASK=test:integration
matrix:
  fast_finish: true
  allow_failures:
    - TASK=test:integration
script:
  - |
    if [[ "$TASK" == "srcclr" ]]
    then
        echo "Starting Source clear ..."
        curl -sSL https://download.sourceclear.com/ci.sh | bash
    else
        echo "Running tests"
        yarn run $TASK
    fi
cache: yarn
branches:
  only: [master]
